"""create url-view-log model

Revision ID: 47a8cb3e7838
Revises: 9350326c41d8
Create Date: 2025-08-29 23:08:49.996627

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "47a8cb3e7838"
down_revision: Union[str, Sequence[str], None] = "9350326c41d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
