"""make created_at aware in shorturl

Revision ID: 9350326c41d8
Revises: 86ee448f32d2
Create Date: 2025-08-29 19:52:25.291392

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9350326c41d8"
down_revision: Union[str, Sequence[str], None] = "86ee448f32d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_shorturl_original_url"), "shorturl", ["original_url"], unique=False)
    op.create_index(op.f("ix_shorturl_short_code"), "shorturl", ["short_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shorturl_short_code"), table_name="shorturl")
    op.drop_index(op.f("ix_shorturl_original_url"), table_name="shorturl")
    # ### end Alembic commands ###
