"""add_urlviewlog_table

Revision ID: 9bcfec6163bc
Revises: 47a8cb3e7838
Create Date: 2025-08-30 01:47:27.845628

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bcfec6163bc"
down_revision: Union[str, Sequence[str], None] = "47a8cb3e7838"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urlviewlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shorturl_id", sa.Integer(), nullable=False),
        sa.Column("viewed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shorturl_id"],
            ["shorturl.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("is_shorturl_processed", "urlviewlog", ["shorturl_id", "processed"], unique=False)
    op.create_index(op.f("ix_urlviewlog_processed"), "urlviewlog", ["processed"], unique=False)
    op.create_index(op.f("ix_urlviewlog_shorturl_id"), "urlviewlog", ["shorturl_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urlviewlog_shorturl_id"), table_name="urlviewlog")
    op.drop_index(op.f("ix_urlviewlog_processed"), table_name="urlviewlog")
    op.drop_index("is_shorturl_processed", table_name="urlviewlog")
    op.drop_table("urlviewlog")
    # ### end Alembic commands ###
